; Access Specific

projects[acc_layout][type] = "module"
projects[acc_layout][download][type] = "git"
projects[acc_layout][download][url] = "https://github.com/hraccess/acc_layout.git"
projects[acc_layout][download][branch] = "master"
projects[acc_layout][subdir] = "access"

projects[acc_incidents][type] = "module"
projects[acc_incidents][download][type] = "git"
projects[acc_incidents][download][url] = "https://github.com/hraccess/acc_incidents.git"
projects[acc_incidents][download][branch] = "master"
projects[acc_incidents][subdir] = "access"

projects[acc_impacts][type] = "module"
projects[acc_impacts][download][type] = "git"
projects[acc_impacts][download][url] = "https://github.com/hraccess/acc_impacts.git"
projects[acc_impacts][download][branch] = "master"
projects[acc_impacts][subdir] = "access"

projects[acc_incident_types][type] = "module"
projects[acc_incident_types][download][type] = "git"
projects[acc_incident_types][download][url] = "https://github.com/hraccess/acc_incident_types.git"
projects[acc_incident_types][download][branch] = "master"
projects[acc_incident_types][subdir] = "access"

projects[acc_restrictions][type] = "module"
projects[acc_restrictions][download][type] = "git"
projects[acc_restrictions][download][url] = "https://github.com/hraccess/acc_restrictions.git"
projects[acc_restrictions][download][branch] = "master"
projects[acc_restrictions][subdir] = "access"

projects[acc_impediments][type] = "module"
projects[acc_impediments][download][type] = "git"
projects[acc_impediments][download][url] = "https://github.com/hraccess/acc_impediments.git"
projects[acc_impediments][download][branch] = "master"
projects[acc_impediments][subdir] = "access"

projects[acc_constraints][type] = "module"
projects[acc_constraints][download][type] = "git"
projects[acc_constraints][download][url] = "https://github.com/hraccess/acc_constraints.git"
projects[acc_constraints][download][branch] = "master"
projects[acc_constraints][subdir] = "access"

projects[acc_temp_const][type] = "module"
projects[acc_temp_const][download][type] = "git"
projects[acc_temp_const][download][url] = "https://github.com/hraccess/acc_temp_const.git"
projects[acc_temp_const][download][branch] = "master"
projects[acc_temp_const][subdir] = "access"

projects[acc_action_taken][type] = "module"
projects[acc_action_taken][download][type] = "git"
projects[acc_action_taken][download][url] = "https://github.com/hraccess/acc_action_taken.git"
projects[acc_action_taken][download][branch] = "master"
projects[acc_action_taken][subdir] = "access"

projects[acc_policy][type] = "module"
projects[acc_policy][download][type] = "git"
projects[acc_policy][download][url] = "https://github.com/hraccess/acc_policy.git"
projects[acc_policy][download][branch] = "master"
projects[acc_policy][subdir] = "access"

projects[acc_organizations][type] = "module"
projects[acc_organizations][download][type] = "git"
projects[acc_organizations][download][url] = "https://github.com/hraccess/acc_organizations.git"
projects[acc_organizations][download][branch] = "master"
projects[acc_organizations][subdir] = "access"

projects[acc_type_proc][type] = "module"
projects[acc_type_proc][download][type] = "git"
projects[acc_type_proc][download][url] = "https://github.com/hraccess/acc_type_proc.git"
projects[acc_type_proc][download][branch] = "master"
projects[acc_type_proc][subdir] = "access"

projects[acc_admin_req][type] = "module"
projects[acc_admin_req][download][type] = "git"
projects[acc_admin_req][download][url] = "https://github.com/hraccess/acc_admin_req.git"
projects[acc_admin_req][download][branch] = "master"
projects[acc_admin_req][subdir] = "access"

projects[acc_units][type] = "module"
projects[acc_units][download][type] = "git"
projects[acc_units][download][url] = "https://github.com/hraccess/acc_units.git"
projects[acc_units][download][branch] = "master"
projects[acc_units][subdir] = "access"

projects[acc_events][type] = "module"
projects[acc_events][download][type] = "git"
projects[acc_events][download][url] = "https://github.com/hraccess/acc_events.git"
projects[acc_events][download][branch] = "master"
projects[acc_events][subdir] = "access"
