projects[hr_core][type] = "module"
projects[hr_core][download][type] = "git"
projects[hr_core][download][url] = "https://github.com/humanitarianresponse/hr_core.git"
projects[hr_core][download][branch] = "7.x-2.x"
projects[hr_core][subdir] = "hr"

projects[hr_bundles][type] = "module"
projects[hr_bundles][download][type] = "git"
projects[hr_bundles][download][url] = "https://github.com/humanitarianresponse/hr_bundles.git"
projects[hr_bundles][download][branch] = "7.x-2.x"
projects[hr_bundles][subdir] = "hr"

projects[hr_locations][type] = "module"
projects[hr_locations][download][type] = "git"
projects[hr_locations][download][url] = "https://github.com/humanitarianresponse/hr_locations.git"
projects[hr_locations][download][branch] = "7.x-2.x"
projects[hr_locations][subdir] = "hr"

projects[hr_operations][type] = "module"
projects[hr_operations][download][type] = "git"
projects[hr_operations][download][url] = "https://github.com/humanitarianresponse/hr_operations.git"
projects[hr_operations][download][branch] = "7.x-2.x"
projects[hr_operations][subdir] = "hr"

projects[hr_organizations][type] = "module"
projects[hr_organizations][download][type] = "git"
projects[hr_organizations][download][url] = "https://github.com/humanitarianresponse/hr_organizations.git"
projects[hr_organizations][download][branch] = "7.x-2.x"
projects[hr_organizations][subdir] = "hr"

projects[hr_sectors][type] = "module"
projects[hr_sectors][download][type] = "git"
projects[hr_sectors][download][url] = "https://github.com/humanitarianresponse/hr_sectors.git"
projects[hr_sectors][download][branch] = "7.x-2.x"
projects[hr_sectors][subdir] = "hr"

projects[hr_spaces][type] = "module"
projects[hr_spaces][download][type] = "git"
projects[hr_spaces][download][url] = "https://github.com/humanitarianresponse/hr_spaces.git"
projects[hr_spaces][download][branch] = "7.x-2.x"
projects[hr_spaces][subdir] = "hr"

projects[hr_layout][type] = "module"
projects[hr_layout][download][type] = "git"
projects[hr_layout][download][url] = "https://github.com/humanitarianresponse/hr_layout.git"
projects[hr_layout][download][branch] = "7.x-2.x"
projects[hr_layout][subdir] = "hr"

projects[hr_pages][type] = "module"
projects[hr_pages][download][type] = "git"
projects[hr_pages][download][url] = "https://github.com/humanitarianresponse/hr_pages.git"
projects[hr_pages][download][branch] = "7.x-2.x"
projects[hr_pages][subdir] = "hr"

projects[hr_contacts][type] = "module"
projects[hr_contacts][download][type] = "git"
projects[hr_contacts][download][url] = "https://github.com/humanitarianresponse/hr_contacts.git"
projects[hr_contacts][download][branch] = "7.x-2.x"
projects[hr_contacts][subdir] = "hr"

projects[hr_documents][type] = "module"
projects[hr_documents][download][type] = "git"
projects[hr_documents][download][url] = "https://github.com/humanitarianresponse/hr_documents.git"
projects[hr_documents][download][branch] = "7.x-2.x"
projects[hr_documents][subdir] = "hr"

projects[hr_disasters][type] = "module"
projects[hr_disasters][download][type] = "git"
projects[hr_disasters][download][url] = "https://github.com/humanitarianresponse/hr_disasters.git"
projects[hr_disasters][download][branch] = "7.x-2.x"
projects[hr_disasters][subdir] = "hr"

projects[hr_fundings][type] = "module"
projects[hr_fundings][download][type] = "git"
projects[hr_fundings][download][url] = "https://github.com/humanitarianresponse/hr_fundings.git"
projects[hr_fundings][download][branch] = "7.x-2.x"
projects[hr_fundings][subdir] = "hr"

projects[hr_job_titles][type] = "module"
projects[hr_job_titles][download][type] = "git"
projects[hr_job_titles][download][url] = "https://github.com/humanitarianresponse/hr_job_titles.git"
projects[hr_job_titles][download][branch] = "7.x-2.x"
projects[hr_job_titles][subdir] = "hr"

projects[hr_offices][type] = "module"
projects[hr_offices][download][type] = "git"
projects[hr_offices][download][url] = "https://github.com/humanitarianresponse/hr_offices.git"
projects[hr_offices][download][branch] = "7.x-2.x"
projects[hr_offices][subdir] = "hr"

projects[hr_search][type] = "module"
projects[hr_search][download][type] = "git"
projects[hr_search][download][url] = "https://github.com/humanitarianresponse/hr_search.git"
projects[hr_search][download][branch] = "7.x-2.x"
projects[hr_search][subdir] = "hr"

projects[hr_themes][type] = "module"
projects[hr_themes][download][type] = "git"
projects[hr_themes][download][url] = "https://github.com/humanitarianresponse/hr_themes.git"
projects[hr_themes][download][branch] = "7.x-2.x"
projects[hr_themes][subdir] = "hr"

projects[hr_users][type] = "module"
projects[hr_users][download][type] = "git"
projects[hr_users][download][url] = "https://github.com/humanitarianresponse/hr_users.git"
projects[hr_users][download][branch] = "7.x-2.x"
projects[hr_users][subdir] = "hr"

projects[hr_help][type] = "module"
projects[hr_help][download][type] = "git"
projects[hr_help][download][url] = "https://github.com/humanitarianresponse/hr_help.git"
projects[hr_help][download][branch] = "7.x-2.x"
projects[hr_help][subdir] = "hr"

projects[hr_notifications][type] = "module"
projects[hr_notifications][download][type] = "git"
projects[hr_notifications][download][url] = "https://github.com/humanitarianresponse/hr_notifications.git"
projects[hr_notifications][download][branch] = "7.x-2.x"
projects[hr_notifications][subdir] = "hr"

projects[hr_events][type] = "module"
projects[hr_events][download][type] = "git"
projects[hr_events][download][url] = "https://github.com/humanitarianresponse/hr_events.git"
projects[hr_events][download][branch] = "7.x-2.x"
projects[hr_events][subdir] = "hr"

projects[hr_migrate][type] = "module"
projects[hr_migrate][download][type] = "git"
projects[hr_migrate][download][url] = "https://github.com/humanitarianresponse/hr_migrate.git"
projects[hr_migrate][download][branch] = "7.x-2.x"
projects[hr_migrate][subdir] = "hr"

projects[hr_news][type] = "module"
projects[hr_news][download][type] = "git"
projects[hr_news][download][url] = "https://github.com/humanitarianresponse/hr_news.git"
projects[hr_news][download][branch] = "7.x-2.x"
projects[hr_news][subdir] = "hr"

projects[hr_tools][type] = "module"
projects[hr_tools][download][type] = "git"
projects[hr_tools][download][url] = "https://github.com/humanitarianresponse/hr_tools.git"
projects[hr_tools][download][branch] = "7.x-2.x"
projects[hr_tools][subdir] = "hr"

projects[hr_indicators][type] = "module"
projects[hr_indicators][download][type] = "git"
projects[hr_indicators][download][url] = "https://github.com/humanitarianresponse/hr_indicators.git"
projects[hr_indicators][download][branch] = "7.x-2.x"
projects[hr_indicators][subdir] = "hr"

projects[hr_wysiwyg][type] = "module"
projects[hr_wysiwyg][download][type] = "git"
projects[hr_wysiwyg][download][url] = "https://github.com/humanitarianresponse/hr_wysiwyg.git"
projects[hr_wysiwyg][download][branch] = "7.x-2.x"
projects[hr_wysiwyg][subdir] = "hr"

projects[hr_webforms][type] = "module"
projects[hr_webforms][download][type] = "git"
projects[hr_webforms][download][url] = "https://github.com/humanitarianresponse/hr_webforms.git"
projects[hr_webforms][download][branch] = "7.x-2.x"
projects[hr_webforms][subdir] = "hr"

projects[hr_datasets][type] = "module"
projects[hr_datasets][download][type] = "git"
projects[hr_datasets][download][url] = "https://github.com/humanitarianresponse/hr_datasets.git"
projects[hr_datasets][download][branch] = "7.x-2.x"
projects[hr_datasets][subdir] = "hr"

projects[hr_bookmarks][type] = "module"
projects[hr_bookmarks][download][type] = "git"
projects[hr_bookmarks][download][url] = "https://github.com/humanitarianresponse/hr_bookmarks.git"
projects[hr_bookmarks][download][branch] = "7.x-2.x"
projects[hr_bookmarks][subdir] = "hr"

projects[hr_infographics][type] = "module"
projects[hr_infographics][download][type] = "git"
projects[hr_infographics][download][url] = "https://github.com/humanitarianresponse/hr_infographics.git"
projects[hr_infographics][download][branch] = "7.x-2.x"
projects[hr_infographics][subdir] = "hr"

projects[hr_assessments][type] = "module"
projects[hr_assessments][download][type] = "git"
projects[hr_assessments][download][url] = "https://github.com/humanitarianresponse/hr_assessments.git"
projects[hr_assessments][download][branch] = "7.x-2.x"
projects[hr_assessments][subdir] = "hr"

projects[hr_translations][type] = "module"
projects[hr_translations][download][type] = "git"
projects[hr_translations][download][url] = "https://github.com/humanitarianresponse/hr_translations.git"
projects[hr_translations][download][branch] = "7.x-2.x"
projects[hr_translations][subdir] = "hr"

projects[hr_stats][type] = "module"
projects[hr_stats][download][type] = "git"
projects[hr_stats][download][url] = "https://github.com/humanitarianresponse/hr_stats.git"
projects[hr_stats][download][branch] = "7.x-2.x"
projects[hr_stats][subdir] = "hr"

; Themes
; --------

projects[humanitarianresponse][type] = "theme"
projects[humanitarianresponse][download][type] = "git"
projects[humanitarianresponse][download][url] = "https://github.com/humanitarianresponse/theme.git"
projects[humanitarianresponse][download][branch] = "7.x-2.x"

