projects[humanitarianresponse_documents][type] = "module"
projects[humanitarianresponse_documents][download][type] = "git"
projects[humanitarianresponse_documents][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_documents.git"
projects[humanitarianresponse_documents][download][branch] = "master"
projects[humanitarianresponse_documents][subdir] = "hr"

projects[humanitarianresponse_clusters][type] = "module"
projects[humanitarianresponse_clusters][download][type] = "git"
projects[humanitarianresponse_clusters][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_clusters.git"
projects[humanitarianresponse_clusters][download][branch] = "master"
projects[humanitarianresponse_clusters][subdir] = "hr"

projects[humanitarianresponse_clusters_menu][type] = "module"
projects[humanitarianresponse_clusters_menu][download][type] = "git"
projects[humanitarianresponse_clusters_menu][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_clusters_menu.git"
projects[humanitarianresponse_clusters_menu][download][branch] = "master"
projects[humanitarianresponse_clusters_menu][subdir] = "hr"

projects[humanitarianresponse_locations][type] = "module"
projects[humanitarianresponse_locations][download][type] = "git"
projects[humanitarianresponse_locations][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_locations.git"
projects[humanitarianresponse_locations][download][branch] = "master"
projects[humanitarianresponse_locations][subdir] = "hr"

projects[humanitarianresponse_emergencies][type] = "module"
projects[humanitarianresponse_emergencies][download][type] = "git"
projects[humanitarianresponse_emergencies][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_emergencies.git"
projects[humanitarianresponse_emergencies][download][branch] = "master"
projects[humanitarianresponse_emergencies][subdir] = "hr"

projects[humanitarianresponse_themes][type] = "module"
projects[humanitarianresponse_themes][download][type] = "git"
projects[humanitarianresponse_themes][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_themes.git"
projects[humanitarianresponse_themes][download][branch] = "master"
projects[humanitarianresponse_themes][subdir] = "hr"

projects[humanitarianresponse_organizations][type] = "module"
projects[humanitarianresponse_organizations][download][type] = "git"
projects[humanitarianresponse_organizations][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_organizations.git"
projects[humanitarianresponse_organizations][download][branch] = "master"
projects[humanitarianresponse_organizations][subdir] = "hr"

projects[humanitarianresponse_events][type] = "module"
projects[humanitarianresponse_events][download][type] = "git"
projects[humanitarianresponse_events][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_events.git"
projects[humanitarianresponse_events][download][branch] = "master"
projects[humanitarianresponse_events][subdir] = "hr"

projects[humanitarianresponse_links][type] = "module"
projects[humanitarianresponse_links][download][type] = "git"
projects[humanitarianresponse_links][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_links.git"
projects[humanitarianresponse_links][download][branch] = "master"
projects[humanitarianresponse_links][subdir] = "hr"

projects[humanitarianresponse_news][type] = "module"
projects[humanitarianresponse_news][download][type] = "git"
projects[humanitarianresponse_news][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_news.git"
projects[humanitarianresponse_news][download][branch] = "master"
projects[humanitarianresponse_news][subdir] = "hr"

projects[humanitarianresponse_maps][type] = "module"
projects[humanitarianresponse_maps][download][type] = "git"
projects[humanitarianresponse_maps][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_maps.git"
projects[humanitarianresponse_maps][download][branch] = "master"
projects[humanitarianresponse_maps][subdir] = "hr"

projects[humanitarianresponse_users][type] = "module"
projects[humanitarianresponse_users][download][type] = "git"
projects[humanitarianresponse_users][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_users.git"
projects[humanitarianresponse_users][download][branch] = "master"
projects[humanitarianresponse_users][subdir] = "hr"

projects[humanitarianresponse_minimal_layout][type] = "module"
projects[humanitarianresponse_minimal_layout][download][type] = "git"
projects[humanitarianresponse_minimal_layout][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_minimal_layout.git"
projects[humanitarianresponse_minimal_layout][download][branch] = "master"
projects[humanitarianresponse_minimal_layout][subdir] = "hr"

projects[humanitarianresponse_layout][type] = "module"
projects[humanitarianresponse_layout][download][type] = "git"
projects[humanitarianresponse_layout][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_layout.git"
projects[humanitarianresponse_layout][download][branch] = "master"
projects[humanitarianresponse_layout][subdir] = "hr"

projects[humanitarianresponse_coordination][type] = "module"
projects[humanitarianresponse_coordination][download][type] = "git"
projects[humanitarianresponse_coordination][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_coordination.git"
projects[humanitarianresponse_coordination][download][branch] = "master"
projects[humanitarianresponse_coordination][subdir] = "hr"

projects[humanitarianresponse_funding][type] = "module"
projects[humanitarianresponse_funding][download][type] = "git"
projects[humanitarianresponse_funding][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_funding.git"
projects[humanitarianresponse_funding][download][branch] = "master"
projects[humanitarianresponse_funding][subdir] = "hr"

projects[humanitarianresponse_funding_menu][type] = "module"
projects[humanitarianresponse_funding_menu][download][type] = "git"
projects[humanitarianresponse_funding_menu][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_funding_menu.git"
projects[humanitarianresponse_funding_menu][download][branch] = "master"
projects[humanitarianresponse_funding_menu][subdir] = "hr"

projects[humanitarianresponse_highlight][type] = "module"
projects[humanitarianresponse_highlight][download][type] = "git"
projects[humanitarianresponse_highlight][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_highlight.git"
projects[humanitarianresponse_highlight][download][branch] = "master"
projects[humanitarianresponse_highlight][subdir] = "hr"

projects[humanitarianresponse_display][type] = "module"
projects[humanitarianresponse_display][download][type] = "git"
projects[humanitarianresponse_display][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_display.git"
projects[humanitarianresponse_display][download][branch] = "master"
projects[humanitarianresponse_display][subdir] = "hr"

projects[humanitarianresponse_contacts][type] = "module"
projects[humanitarianresponse_contacts][download][type] = "git"
projects[humanitarianresponse_contacts][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_contacts.git"
projects[humanitarianresponse_contacts][download][branch] = "master"
projects[humanitarianresponse_contacts][subdir] = "hr"

projects[humanitarianresponse_search][type] = "module"
projects[humanitarianresponse_search][download][type] = "git"
projects[humanitarianresponse_search][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_search.git"
projects[humanitarianresponse_search][download][branch] = "master"
projects[humanitarianresponse_search][subdir] = "hr"

projects[humanitarianresponse_media][type] = "module"
projects[humanitarianresponse_media][download][type] = "git"
projects[humanitarianresponse_media][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_media.git"
projects[humanitarianresponse_media][download][branch] = "master"
projects[humanitarianresponse_media][subdir] = "hr"

projects[humanitarianresponse_assessments][type] = "module"
projects[humanitarianresponse_assessments][download][type] = "git"
projects[humanitarianresponse_assessments][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_assessments.git"
projects[humanitarianresponse_assessments][download][branch] = "master"
projects[humanitarianresponse_assessments][subdir] = "hr"

projects[humanitarianresponse_profiles][type] = "module"
projects[humanitarianresponse_profiles][download][type] = "git"
projects[humanitarianresponse_profiles][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_profiles.git"
projects[humanitarianresponse_profiles][download][branch] = "master"
projects[humanitarianresponse_profiles][subdir] = "hr"

projects[humanitarianresponse_core][type] = "module"
projects[humanitarianresponse_core][download][type] = "git"
projects[humanitarianresponse_core][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_core.git"
projects[humanitarianresponse_core][download][branch] = "master"
projects[humanitarianresponse_core][subdir] = "hr"

projects[humanitarianresponse_i18n][type] = "module"
projects[humanitarianresponse_i18n][download][type] = "git"
projects[humanitarianresponse_i18n][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_i18n.git"
projects[humanitarianresponse_i18n][download][branch] = "master"
projects[humanitarianresponse_i18n][subdir] = "hr"

projects[humanitarianresponse_mapping][type] = "module"
projects[humanitarianresponse_mapping][download][type] = "git"
projects[humanitarianresponse_mapping][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_mapping.git"
projects[humanitarianresponse_mapping][download][branch] = "master"
projects[humanitarianresponse_mapping][subdir] = "hr"

projects[humanitarianresponse_page][type] = "module"
projects[humanitarianresponse_page][download][type] = "git"
projects[humanitarianresponse_page][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_page.git"
projects[humanitarianresponse_page][download][branch] = "master"
projects[humanitarianresponse_page][subdir] = "hr"

projects[humanitarianresponse_emergency_menu][type] = "module"
projects[humanitarianresponse_emergency_menu][download][type] = "git"
projects[humanitarianresponse_emergency_menu][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_emergency_menu.git"
projects[humanitarianresponse_emergency_menu][download][branch] = "master"
projects[humanitarianresponse_emergency_menu][subdir] = "hr"

projects[humanitarianresponse_stats][type] = "module"
projects[humanitarianresponse_stats][download][type] = "git"
projects[humanitarianresponse_stats][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_stats.git"
projects[humanitarianresponse_stats][download][branch] = "master"
projects[humanitarianresponse_stats][subdir] = "hr"

projects[humanitarianresponse_aggregator][type] = "module"
projects[humanitarianresponse_aggregator][download][type] = "git"
projects[humanitarianresponse_aggregator][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_aggregator.git"
projects[humanitarianresponse_aggregator][download][branch] = "master"
projects[humanitarianresponse_aggregator][subdir] = "hr"

projects[hr_mapping_styles][type] = "module"
projects[hr_mapping_styles][download][type] = "git"
projects[hr_mapping_styles][download][url] = "https://github.com/humanitarianresponse/hr_mapping_styles.git"
projects[hr_mapping_styles][download][branch] = "master"
projects[hr_mapping_styles][subdir] = "hr"

projects[hr_login][type] = "module"
projects[hr_login][download][type] = "git"
projects[hr_login][download][url] = "https://github.com/humanitarianresponse/hr_login.git"
projects[hr_login][download][branch] = "master"
projects[hr_login][subdir] = "hr"

projects[hr_sectors][type] = "module"
projects[hr_sectors][download][type] = "git"
projects[hr_sectors][download][url] = "https://github.com/humanitarianresponse/hr_sectors.git"
projects[hr_sectors][download][branch] = "master"
projects[hr_sectors][subdir] = "hr"

projects[hr_assessments_sectors][type] = "module"
projects[hr_assessments_sectors][download][type] = "git"
projects[hr_assessments_sectors][download][url] = "https://github.com/humanitarianresponse/hr_assessments_sectors.git"
projects[hr_assessments_sectors][download][branch] = "master"
projects[hr_assessments_sectors][subdir] = "hr"

projects[hr_contacts_sectors][type] = "module"
projects[hr_contacts_sectors][download][type] = "git"
projects[hr_contacts_sectors][download][url] = "https://github.com/humanitarianresponse/hr_contacts_sectors.git"
projects[hr_contacts_sectors][download][branch] = "master"
projects[hr_contacts_sectors][subdir] = "hr"

projects[hr_documents_sectors][type] = "module"
projects[hr_documents_sectors][download][type] = "git"
projects[hr_documents_sectors][download][url] = "https://github.com/humanitarianresponse/hr_documents_sectors.git"
projects[hr_documents_sectors][download][branch] = "master"
projects[hr_documents_sectors][subdir] = "hr"

projects[hr_emergency_menu_sectors][type] = "module"
projects[hr_emergency_menu_sectors][download][type] = "git"
projects[hr_emergency_menu_sectors][download][url] = "https://github.com/humanitarianresponse/hr_emergency_menu_sectors.git"
projects[hr_emergency_menu_sectors][download][branch] = "master"
projects[hr_emergency_menu_sectors][subdir] = "hr"

projects[hr_events_sectors][type] = "module"
projects[hr_events_sectors][download][type] = "git"
projects[hr_events_sectors][download][url] = "https://github.com/humanitarianresponse/hr_events_sectors.git"
projects[hr_events_sectors][download][branch] = "master"
projects[hr_events_sectors][subdir] = "hr"

projects[hr_highlight_sectors][type] = "module"
projects[hr_highlight_sectors][download][type] = "git"
projects[hr_highlight_sectors][download][url] = "https://github.com/humanitarianresponse/hr_highlight_sectors.git"
projects[hr_highlight_sectors][download][branch] = "master"
projects[hr_highlight_sectors][subdir] = "hr"

projects[hr_links_sectors][type] = "module"
projects[hr_links_sectors][download][type] = "git"
projects[hr_links_sectors][download][url] = "https://github.com/humanitarianresponse/hr_links_sectors.git"
projects[hr_links_sectors][download][branch] = "master"
projects[hr_links_sectors][subdir] = "hr"

projects[hr_news_sectors][type] = "module"
projects[hr_news_sectors][download][type] = "git"
projects[hr_news_sectors][download][url] = "https://github.com/humanitarianresponse/hr_news_sectors.git"
projects[hr_news_sectors][download][branch] = "master"
projects[hr_news_sectors][subdir] = "hr"

projects[hr_visuals_sectors][type] = "module"
projects[hr_visuals_sectors][download][type] = "git"
projects[hr_visuals_sectors][download][url] = "https://github.com/humanitarianresponse/hr_visuals_sectors.git"
projects[hr_visuals_sectors][download][branch] = "master"
projects[hr_visuals_sectors][subdir] = "hr"

projects[hr_assessments_i18n][type] = "module"
projects[hr_assessments_i18n][download][type] = "git"
projects[hr_assessments_i18n][download][url] = "https://github.com/humanitarianresponse/hr_assessments_i18n.git"
projects[hr_assessments_i18n][download][branch] = "master"
projects[hr_assessments_i18n][subdir] = "hr"

projects[hr_private][type] = "module"
projects[hr_private][download][type] = "git"
projects[hr_private][download][url] = "https://github.com/humanitarianresponse/hr_private.git"
projects[hr_private][download][branch] = "master"
projects[hr_private][subdir] = "hr"

projects[hr_reliefweb][type] = "module"
projects[hr_reliefweb][download][type] = "git"
projects[hr_reliefweb][download][url] = "https://github.com/humanitarianresponse/hr_reliefweb.git"
projects[hr_reliefweb][download][branch] = "master"
projects[hr_reliefweb][subdir] = "hr"

projects[hr_resp_img][type] = "module"
projects[hr_resp_img][download][type] = "git"
projects[hr_resp_img][download][url] = "https://github.com/humanitarianresponse/hr_resp_img.git"
projects[hr_resp_img][download][branch] = "master"
projects[hr_resp_img][subdir] = "hr"

projects[hr_news_slideshow][type] = "module"
projects[hr_news_slideshow][download][type] = "git"
projects[hr_news_slideshow][download][url] = "https://github.com/humanitarianresponse/hr_news_slideshow.git"
projects[hr_news_slideshow][download][branch] = "master"
projects[hr_news_slideshow][subdir] = "hr"

projects[hr_help][type] = "module"
projects[hr_help][download][type] = "git"
projects[hr_help][download][url] = "https://github.com/humanitarianresponse/hr_help.git"
projects[hr_help][download][branch] = "master"
projects[hr_help][subdir] = "hr"

projects[hr_print][type] = "module"
projects[hr_print][download][type] = "git"
projects[hr_print][download][url] = "https://github.com/humanitarianresponse/hr_print.git"
projects[hr_print][download][branch] = "master"
projects[hr_print][subdir] = "hr"

projects[hr_sitrep][type] = "module"
projects[hr_sitrep][download][type] = "git"
projects[hr_sitrep][download][url] = "https://github.com/humanitarianresponse/hr_sitrep.git"
projects[hr_sitrep][download][branch] = "master"
projects[hr_sitrep][subdir] = "hr"

projects[hr_cluster_objectives][type] = "module"
projects[hr_cluster_objectives][download][type] = "git"
projects[hr_cluster_objectives][download][url] = "https://github.com/humanitarianresponse/hr_cluster_objectives.git"
projects[hr_cluster_objectives][download][branch] = "master"
projects[hr_cluster_objectives][subdir] = "hr"

projects[hr_indicator_data][type] = "module"
projects[hr_indicator_data][download][type] = "git"
projects[hr_indicator_data][download][url] = "https://github.com/humanitarianresponse/hr_indicator_data.git"
projects[hr_indicator_data][download][branch] = "master"
projects[hr_indicator_data][subdir] = "hr"

projects[hr_indicator_definitions][type] = "module"
projects[hr_indicator_definitions][download][type] = "git"
projects[hr_indicator_definitions][download][url] = "https://github.com/humanitarianresponse/hr_indicator_definitions.git"
projects[hr_indicator_definitions][download][branch] = "master"
projects[hr_indicator_definitions][subdir] = "hr"

projects[hr_sectoral_analysis][type] = "module"
projects[hr_sectoral_analysis][download][type] = "git"
projects[hr_sectoral_analysis][download][url] = "https://github.com/humanitarianresponse/hr_sectoral_analysis.git"
projects[hr_sectoral_analysis][download][branch] = "master"
projects[hr_sectoral_analysis][subdir] = "hr"

projects[hr_revisions][type] = "module"
projects[hr_revisions][download][type] = "git"
projects[hr_revisions][download][url] = "https://github.com/humanitarianresponse/hr_revisions.git"
projects[hr_revisions][download][branch] = "master"
projects[hr_revisions][subdir] = "hr"

projects[hr_incidents][type] = "module"
projects[hr_incidents][download][type] = "git"
projects[hr_incidents][download][url] = "https://github.com/humanitarianresponse/hr_incidents.git"
projects[hr_incidents][download][branch] = "master"
projects[hr_incidents][subdir] = "hr"

projects[hr_keywords][type] = "module"
projects[hr_keywords][download][type] = "git"
projects[hr_keywords][download][url] = "https://github.com/humanitarianresponse/hr_keywords.git"
projects[hr_keywords][download][branch] = "master"
projects[hr_keywords][subdir] = "hr"

projects[hr_geographic_level][type] = "module"
projects[hr_geographic_level][download][type] = "git"
projects[hr_geographic_level][download][url] = "https://github.com/humanitarianresponse/hr_geographic_level.git"
projects[hr_geographic_level][download][branch] = "master"
projects[hr_geographic_level][subdir] = "hr"

projects[hr_fts][type] = "module"
projects[hr_fts][download][type] = "git"
projects[hr_fts][download][url] = "https://github.com/humanitarianresponse/hr_fts.git"
projects[hr_fts][download][branch] = "master"
projects[hr_fts][subdir] = "hr"

projects[hr_cluster_instance][type] = "module"
projects[hr_cluster_instance][download][type] = "git"
projects[hr_cluster_instance][download][url] = "https://github.com/humanitarianresponse/hr_cluster_instance.git"
projects[hr_cluster_instance][download][branch] = "master"
projects[hr_cluster_instance][subdir] = "hr"

projects[hr_blog][type] = "module"
projects[hr_blog][download][type] = "git"
projects[hr_blog][download][url] = "https://github.com/humanitarianresponse/hr_blog.git"
projects[hr_blog][download][branch] = "master"
projects[hr_blog][subdir] = "hr"

projects[hr_op_presence][type] = "module"
projects[hr_op_presence][download][type] = "git"
projects[hr_op_presence][download][url] = "https://github.com/humanitarianresponse/hr_op_presence.git"
projects[hr_op_presence][download][branch] = "master"
projects[hr_op_presence][subdir] = "hr"

projects[hr_faceted_layout][type] = "module"
projects[hr_faceted_layout][download][type] = "git"
projects[hr_faceted_layout][download][url] = "https://github.com/humanitarianresponse/hr_faceted_layout.git"
projects[hr_faceted_layout][download][branch] = "master"
projects[hr_faceted_layout][subdir] = "hr"

projects[hr_job_title][type] = "module"
projects[hr_job_title][download][type] = "git"
projects[hr_job_title][download][url] = "https://github.com/humanitarianresponse/hr_job_title.git"
projects[hr_job_title][download][branch] = "master"
projects[hr_job_title][subdir] = "hr"

projects[hr_theme][type] = "module"
projects[hr_theme][download][type] = "git"
projects[hr_theme][download][url] = "https://github.com/humanitarianresponse/hr_theme.git"
projects[hr_theme][download][branch] = "master"
projects[hr_theme][subdir] = "hr"

projects[hr_boxes][type] = "module"
projects[hr_boxes][download][type] = "git"
projects[hr_boxes][download][url] = "https://github.com/humanitarianresponse/hr_boxes.git"
projects[hr_boxes][download][branch] = "master"
projects[hr_boxes][subdir] = "hr"

projects[hr_iframe][type] = "module"
projects[hr_iframe][download][type] = "git"
projects[hr_iframe][download][url] = "https://github.com/humanitarianresponse/hr_iframe.git"
projects[hr_iframe][download][branch] = "master"
projects[hr_iframe][subdir] = "hr"

projects[hr_search_map][type] = "module"
projects[hr_search_map][download][type] = "git"
projects[hr_search_map][download][url] = "https://github.com/humanitarianresponse/hr_search_map.git"
projects[hr_search_map][download][branch] = "master"
projects[hr_search_map][subdir] = "hr"

; Themes
; --------

projects[humanitarianresponse][type] = "theme"
projects[humanitarianresponse][download][type] = "git"
projects[humanitarianresponse][download][url] = "https://github.com/humanitarianresponse/theme.git"
projects[humanitarianresponse][download][branch] = "master"

; Profiles
; ---------
projects[emergency_site][type] = "profile"
projects[emergency_site][download][type] = "git"
projects[emergency_site][download][url] = "https://github.com/humanitarianresponse/emergency_profile.git"
projects[emergency_site][download][branch] = "master"

projects[humanitarianresponse_minimal][type] = "profile"
projects[humanitarianresponse_minimal][download][type] = "git"
projects[humanitarianresponse_minimal][download][url] = "https://github.com/humanitarianresponse/humanitarianresponse_minimal.git"
projects[humanitarianresponse_minimal][download][branch] = "master"
