projects[hr_core][type] = "module"
projects[hr_core][download][type] = "git"
projects[hr_core][download][url] = "https://github.com/humanitarianresponse/hr_core.git"
projects[hr_core][download][branch] = "7.x-2.x"
projects[hr_core][subdir] = "hr"

projects[hr_bundles][type] = "module"
projects[hr_bundles][download][type] = "git"
projects[hr_bundles][download][url] = "https://github.com/humanitarianresponse/hr_bundles.git"
projects[hr_bundles][download][branch] = "7.x-2.x"
projects[hr_bundles][subdir] = "hr"

projects[hr_locations][type] = "module"
projects[hr_locations][download][type] = "git"
projects[hr_locations][download][url] = "https://github.com/humanitarianresponse/hr_locations.git"
projects[hr_locations][download][branch] = "7.x-2.x"
projects[hr_locations][subdir] = "hr"

projects[hr_operations][type] = "module"
projects[hr_operations][download][type] = "git"
projects[hr_operations][download][url] = "https://github.com/humanitarianresponse/hr_operations.git"
projects[hr_operations][download][branch] = "7.x-2.x"
projects[hr_operations][subdir] = "hr"

projects[hr_organizations][type] = "module"
projects[hr_organizations][download][type] = "git"
projects[hr_organizations][download][url] = "https://github.com/humanitarianresponse/hr_organizations.git"
projects[hr_organizations][download][branch] = "7.x-2.x"
projects[hr_organizations][subdir] = "hr"

projects[hr_sectors][type] = "module"
projects[hr_sectors][download][type] = "git"
projects[hr_sectors][download][url] = "https://github.com/humanitarianresponse/hr_sectors.git"
projects[hr_sectors][download][branch] = "7.x-2.x"
projects[hr_sectors][subdir] = "hr"

projects[hr_spaces][type] = "module"
projects[hr_spaces][download][type] = "git"
projects[hr_spaces][download][url] = "https://github.com/humanitarianresponse/hr_spaces.git"
projects[hr_spaces][download][branch] = "7.x-2.x"
projects[hr_spaces][subdir] = "hr"

projects[hr_layout][type] = "module"
projects[hr_layout][download][type] = "git"
projects[hr_layout][download][url] = "https://github.com/humanitarianresponse/hr_layout.git"
projects[hr_layout][download][branch] = "7.x-2.x"
projects[hr_layout][subdir] = "hr"

projects[hr_pages][type] = "module"
projects[hr_pages][download][type] = "git"
projects[hr_pages][download][url] = "https://github.com/humanitarianresponse/hr_pages.git"
projects[hr_pages][download][branch] = "7.x-2.x"
projects[hr_pages][subdir] = "hr"

projects[hr_contacts][type] = "module"
projects[hr_contacts][download][type] = "git"
projects[hr_contacts][download][url] = "https://github.com/humanitarianresponse/hr_contacts.git"
projects[hr_contacts][download][branch] = "7.x-2.x"
projects[hr_contacts][subdir] = "hr"

projects[hr_documents][type] = "module"
projects[hr_documents][download][type] = "git"
projects[hr_documents][download][url] = "https://github.com/humanitarianresponse/hr_documents.git"
projects[hr_documents][download][branch] = "7.x-2.x"
projects[hr_documents][subdir] = "hr"

projects[hr_emergencies][type] = "module"
projects[hr_emergencies][download][type] = "git"
projects[hr_emergencies][download][url] = "https://github.com/humanitarianresponse/hr_emergencies.git"
projects[hr_emergencies][download][branch] = "7.x-2.x"
projects[hr_emergencies][subdir] = "hr"

projects[hr_fundings][type] = "module"
projects[hr_fundings][download][type] = "git"
projects[hr_fundings][download][url] = "https://github.com/humanitarianresponse/hr_fundings.git"
projects[hr_fundings][download][branch] = "7.x-2.x"
projects[hr_fundings][subdir] = "hr"

projects[hr_job_titles][type] = "module"
projects[hr_job_titles][download][type] = "git"
projects[hr_job_titles][download][url] = "https://github.com/humanitarianresponse/hr_job_titles.git"
projects[hr_job_titles][download][branch] = "7.x-2.x"
projects[hr_job_titles][subdir] = "hr"

projects[hr_offices][type] = "module"
projects[hr_offices][download][type] = "git"
projects[hr_offices][download][url] = "https://github.com/humanitarianresponse/hr_offices.git"
projects[hr_offices][download][branch] = "7.x-2.x"
projects[hr_offices][subdir] = "hr"

projects[hr_search][type] = "module"
projects[hr_search][download][type] = "git"
projects[hr_search][download][url] = "https://github.com/humanitarianresponse/hr_search.git"
projects[hr_search][download][branch] = "7.x-2.x"
projects[hr_search][subdir] = "hr"

projects[hr_themes][type] = "module"
projects[hr_themes][download][type] = "git"
projects[hr_themes][download][url] = "https://github.com/humanitarianresponse/hr_themes.git"
projects[hr_themes][download][branch] = "7.x-2.x"
projects[hr_themes][subdir] = "hr"

projects[hr_users][type] = "module"
projects[hr_users][download][type] = "git"
projects[hr_users][download][url] = "https://github.com/humanitarianresponse/hr_users.git"
projects[hr_users][download][branch] = "7.x-2.x"
projects[hr_users][subdir] = "hr"

; Themes
; --------

projects[humanitarianresponse][type] = "theme"
projects[humanitarianresponse][download][type] = "git"
projects[humanitarianresponse][download][url] = "https://github.com/humanitarianresponse/theme.git"
projects[humanitarianresponse][download][branch] = "7.x-2.x"

